// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VKmfSoft_EHealth_API.Data;

#nullable disable

namespace VKmfSoft_EHealth_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.HospitalBed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HospitalDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalDepartmentId");

                    b.ToTable("HospitalBeds");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.HospitalDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("HospitalDepartments");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.MedicalWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("FirstLanguageID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LicenseValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicalTitle")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OutServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientSurgeryId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PatientSurgeryId");

                    b.ToTable("MedicalWorkers");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("BloodTypeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EmergencyContactDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstLanguageID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("InsuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMobile")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientHealthHistory");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientMedicationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientHealthHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PatientMedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PrescribingDoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientHealthHistoryId");

                    b.ToTable("PatientMedicationHistory");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientHealthHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PatientMedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PerformingMedicalWorkerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ScanTypeId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientHealthHistoryId");

                    b.ToTable("PatientScan");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientSurgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiefOfSurgeryId")
                        .HasColumnType("int");

                    b.Property<int>("ChurgeryRoomNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("HospitalNameId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientAdmissionId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientHealthHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PatientMedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SurgeryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurgeryTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientHealthHistoryId");

                    b.ToTable("PatientSurgery");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientVaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministeringMedicalWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientHealthHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PatientMedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccinationId")
                        .HasColumnType("int");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int");

                    b.Property<string>("VaccineName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientHealthHistoryId");

                    b.ToTable("PatientVaccination");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientVitalSigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OxygenSaturation")
                        .HasColumnType("real");

                    b.Property<int>("Pain")
                        .HasColumnType("int");

                    b.Property<int>("PatientDiagnoseId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientHealthHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("PatientMedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientHealthHistoryId");

                    b.ToTable("PatientVitalSigns");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.TimeShedule.DoctorAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppointmentPlaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DegreeOfUrgency")
                        .HasColumnType("int");

                    b.Property<int>("MedicalWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoctorAppointments");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.HospitalBed", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Hospital.HospitalDepartment", null)
                        .WithMany("PatientBeds")
                        .HasForeignKey("HospitalDepartmentId");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.HospitalDepartment", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Hospital.Hospital", "Hospital")
                        .WithMany("hosptialDepartments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.MedicalWorker", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Hospital.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientSurgery", null)
                        .WithMany("MediacalWorkers")
                        .HasForeignKey("PatientSurgeryId");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.Patient", null)
                        .WithOne("PatientHealthHistory")
                        .HasForeignKey("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientMedicationHistory", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", null)
                        .WithMany("Medications")
                        .HasForeignKey("PatientHealthHistoryId");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientScan", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", null)
                        .WithMany("Scans")
                        .HasForeignKey("PatientHealthHistoryId");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientSurgery", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", null)
                        .WithMany("Surgeries")
                        .HasForeignKey("PatientHealthHistoryId");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientVaccination", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("PatientHealthHistoryId");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientVitalSigns", b =>
                {
                    b.HasOne("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", null)
                        .WithMany("VitalSigns")
                        .HasForeignKey("PatientHealthHistoryId");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.Hospital", b =>
                {
                    b.Navigation("hosptialDepartments");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Hospital.HospitalDepartment", b =>
                {
                    b.Navigation("PatientBeds");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.Patient", b =>
                {
                    b.Navigation("PatientHealthHistory");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientHealthHistory", b =>
                {
                    b.Navigation("Medications");

                    b.Navigation("Scans");

                    b.Navigation("Surgeries");

                    b.Navigation("Vaccinations");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("VKmfSoft_EHealth_API.Models.Domain.Patient.PatientSurgery", b =>
                {
                    b.Navigation("MediacalWorkers");
                });
#pragma warning restore 612, 618
        }
    }
}
